# The 'sources' parameter is a set generated by niv
# from 'sources.nix' and 'sources.json'.
sources:
[
  (self: super:
    {
      # Reflect the sources
      # ===================
      inherit sources;

      # For updating dependencies
      niv = (import sources.niv { pkgs = super; }).niv;

    })
  (import ./ide.nix)
]

